name: Invidious CI

on:
  push:
    branches:
      - "master"
      - "api-only"
  pull_request:
    branches: "*"
  workflow_dispatch:

jobs:
  build-docker-arm64:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Build Docker ARM64 image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.arm64
          platforms: linux/arm64/v8
          build-args: release=0

      - name: Test Docker
        run: while curl -Isf http://localhost:3000; do sleep 1; done
