name: Invidious CI

on:
  push:
    branches:
      - "master"
      - "api-only"
  pull_request:
    branches: "*"
  workflow_dispatch:

jobs:
  build-docker-arm64:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.3.0
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8

      - name: Build Docker ARM64 image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.arm64
          platforms: linux/arm64/v8
          build-args: release=0
